c++ script

diff --git a/scripts/c++ b/scripts/c++
--- a/scripts/c++
+++ b/scripts/c++
@@ -22,40 +22,39 @@ DEV_FLAG="DEV"
 # Or start using strict C++ from now on? decide on this issue later.
 QUALITY_FLAGS="-Wall -Wextra -Werror -pedantic -Wshadow -Wnon-virtual-dtor -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wnull-dereference -Wdouble-promotion -Wformat=2"
 COMPILE_FLAGS="-O2 -std=c++23 $QUALITY_FLAGS -D$DEV_FLAG"
-BIN_PREFIX="c++_"
 
-color-stderr()(set -o pipefail;"$@" 2>&1>&3|sed $'s,.*,\e[31m&\e[m,'>&2)3>&1
+color-stderr() (
+	set -o pipefail
+	"$@" 2>&1 >&3 | sed $'s,.*,\e[31m&\e[m,' >&2
+) 3>&1
 
 # Clean temp folder if there are too many files
 clean_temp_dir() {
-  BIN_TEMP_LIMIT_FILES=30
-  FILES_IN_BIN_TEMP=$(ls $BIN_TEMP 2>/dev/null | wc -l)
+	local bin_temp_limit_files
+	local files_in_bin_temp
 
-  if [[ $FILES_IN_BIN_TEMP -ge $BIN_TEMP_LIMIT_FILES ]]; then
-    rm $BIN_TEMP/*
-  fi
+	bin_temp_limit_files=30
+	files_in_bin_temp=$(find "$BIN_TEMP" -mindepth 1 -maxdepth 1 2>/dev/null | wc -l)
+
+	if [[ $files_in_bin_temp -ge $bin_temp_limit_files ]]; then
+		rm $BIN_TEMP/*
+	fi
 }
 
-if [ -z "$1" ]
-then
-  echo "File path missing" >&2
-  exit 1
+if [ -z "$1" ]; then
+	echo "File path missing" >&2
+	exit 1
 fi
 
 clean_temp_dir
 
-HASH=$(sha1sum $1 | cut -d ' ' -f 1)
+HASH=$(sha1sum "$1" | cut -d ' ' -f 1)
 
-OUT_FILE="$BIN_TEMP/$BIN_PREFIX$HASH"
+OUT_FILE="$BIN_TEMP/$HASH"
 
-if [ ! -f $OUT_FILE ]
-then
-  mkdir -p $BIN_TEMP
-  g++ $1 $COMPILE_FLAGS -o $OUT_FILE
+if [ ! -f "$OUT_FILE" ]; then
+	mkdir -p "$BIN_TEMP"
+	if g++ "$1" $COMPILE_FLAGS -o "$OUT_FILE"; then
+		color-stderr "$OUT_FILE"
+	fi
 fi
-
-if [ $? -eq 0 ]; then
-  # time color-stderr $OUT_FILE
-  color-stderr $OUT_FILE
-fi
-
